config:
  name: app-console
  namespace: application
  replicas: 2
  
image:
  repository: registry.gitlab.com/app-console
  tag: main

imagePullSecrets: 
  name: gitlab-registry
service:
  type: NodePort
  port: 80
env:
  env: staging
  envFromSecret: env-secrets




