config:
  name: app-console
  namespace: application
  replicas: 1
  
image:
  repository: registry.gitlab.com/devops-basic5991728/front-end/app-console
  tag: dev

imagePullSecrets: 
  name: gitlab-registry
service:
  type: NodePort
  port: 4200
env:
  env: staging
  envFromSecret: env-secrets




