config:
  name: user-console
  namespace: application
  replicas: 1
  
image:
  repository: registry.gitlab.com/project_name/front-end/user-console
  tag: dev

imagePullSecrets: 
  name: gitlab-registry
service:
  type: NodePort
  port: 3000
env:
  env: staging
  envFromSecret: env-secrets




