version: '3'
services:
  nginx-gateways:
    container_name: nginx-gateways
    image: nginx:latest
    volumes:
      - "./conf/:/etc/nginx/"
    ports:
      - 80:80
      - 443:443
    network_mode: bridge
