config:
  name: report-service
  namespace: application
  replicas: 2
  
image:
  repository: registry.gitlab.com/report
  tag: main

imagePullSecrets: 
  name: gitlab-registry
service:
  type: NodePort
  port: 4000
env:
  env: staging
  envFromSecret: env-secrets




