config:
  name: payment-service
  namespace: application
  replicas: 2
  
image:
  repository: registry.gitlab.com/devops-basic5991728/back-end/payment-service
  tag: dev

imagePullSecrets: 
  name: gitlab-registry
service:
  type: NodePort
  port: 1323
env:
  env: staging
  envFromSecret: env-secrets




