apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: report-service
  labels:
    app: report-service
spec:
  selector:
    app: report-service
  type: NodePort
  ports:
   - port: 4000
     name: http
     targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: application
  labels:
    app: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: ""registry.gitlab.com/project_name/back-end/report-service:dev""
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: env-secrets
      imagePullSecrets:
      - name: gitlab-registry