apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: payment-service
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  type: NodePort
  ports:
   - port: 1323
     name: http
     targetPort: 1323
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: application
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: ""
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: env-secrets
      imagePullSecrets:
      - name: gitlab-registry