
FROM node:lts-alpine as builder

WORKDIR /app

COPY . /app

ADD package.json /app/

RUN yarn install

COPY . .

RUN yarn build

FROM nginx:alpine

COPY nginx/default.conf /etc/nginx/conf.d/

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist/ /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
