apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: user-console
  labels:
    app: user-console
spec:
  selector:
    app: user-console
  type: NodePort
  ports:
   - port: 3000
     name: http
     targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-console
  namespace: application
  labels:
    app: user-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-console
  template:
    metadata:
      labels:
        app: user-console
    spec:
      containers:
      - name: user-console
        image: "registry.gitlab.com/devops-basic5991728/front-end/user-console:dev"
        imagePullPolicy: Always
        # env:
        #   - name: PORT
        #     value: "6200"
        envFrom:
          - secretRef:
              name: env-secrets
      imagePullSecrets:
      - name: gitlab-registry