apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: app-console
  labels:
    app: app-console
spec:
  selector:
    app: app-console
  type: NodePort
  ports:
   - port: 4200
     name: http
     targetPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-console
  namespace: application
  labels:
    app: app-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-console
  template:
    metadata:
      labels:
        app: app-console
    spec:
      containers:
      - name: app-console
        image: "registry.gitlab.com/project_name/front-end/app-console:dev"
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: env-secrets
      imagePullSecrets:
      - name: gitlab-registry